version: '3.8'
services:
  mysql_8.0:
    image: mysql:8.0.22
    container_name: mysql_8.0_compose
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - /mysql/conf.d:/etc/mysql/conf.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci